### ISSUE TITLE
At the end of generating clicks theres an error

### ISSUE THREAD

**Issue by havemorefaith** [forteus19/zcb-gui#2]
Heres the command prompt when i try generating clicks:

Generating: 100%|████████████████████████████████████████████████████████████████████| 736/736 [00:17<00:00, 41.84it/s]
Exception in thread Thread-3 (generate_clicks):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "generate_clicks.py", line 99, in generate_clicks
  File "pydub\audio_segment.py", line 963, in export
  File "subprocess.py", line 1024, in __init__
  File "subprocess.py", line 1433, in _execute_child
  File "subprocess.py", line 608, in list2cmdline
  File "<frozen os>", line 824, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by forteus19** [comment]
What type of macro did you use

**Comment by havemorefaith** [comment]
i used megahack json

**Comment by forteus19** [comment]
Can you list the steps that you did to get this error, I can't recreate it

**Comment by Door0012** [comment]
do you have ffmpeg?

**Comment by forteus19** [comment]
> do you have ffmpeg?

zcb doesn't use ffmpeg :P

**Comment by havemorefaith** [comment]
> Can you list the steps that you did to get this error, I can't recreate it

I chose my macro, clickpack, output path, and turned normalize output on including every other option and generated clicks. Thats all i did
